---
title: "Exploring the Impact of Queer Media Characters on LGBTQ+ Psychological Well-Being: The Role of Queer Media Consumption, Perceived Authenticity, and Intersectionality"
shorttitle: "Queer Media Characters and LGBTQ+ Well-Being"
author:
  - name: Dingning Yang
    corresponding: true
    orcid: 0009-0008-5546-962X
    email: dingningy@uchicago.edu
    affiliations:
      - name: University of Chicago
        department: Department of Social Sciences
        address: 5105 South Harper Ave.
        city: Chicago
        region: IL
        country: USA
        postal-code: 60615-4156
author-note:
  status-changes: 
    affiliation-change: ~
    deceased: ~
  disclosures:
    study-registration: ~
    data-sharing: ~
    related-report: ~
    conflict-of-interest: ~
    financial-support: ~
    gratitude: ~
    authorship-agreements: ~
abstract: |

  | The growing visibility of the LGBTQ+ community is accompanied by the flourishing of queer characters in media in the information era. While previous studies have explored the double-edged impact of queer media representation on LGBTQ+ individuals’ development, few have compared these effects across different LGBTQ+ subgroups. This study investigates queer media characters’ psychological impacts on LGBTQ+ individuals with different identities, examining the relationship between perceived character authenticity, intersectionality, and characters’ impacts on LGBTQ+ individuals’ psychological well-being using a reliable survey instrument in a worldwide sample. 
  
  | Findings revealed that marginal groups within the LGBTQ+ community, including those from developing countries, gender minorities, and racial minorities, reported higher scores about queer media characters’ positive impacts on psychological well-being compared to their mainstream counterparts. However, in terms of sexual orientation, mainstream groups (i.e., gay and lesbian respondents) showed higher scores. Importantly, the study found strong positive correlations between authenticity ratings, intersectionality ratings, and scores of queer characters’ positive impacts on psychological well-being. 
   
  | This study contributes to a more nuanced understanding of LGBTQ+ individuals' diverse needs and experiences with queer media representation, which has significant implications for media producers, mental health professionals, and LGBTQ+ advocacy groups in fostering more positive and inclusive media representations for the LGBTQ+ community.
keywords: [LGBTQ+ well-being, queer media representations, intersectionality]
format:
  apaquarto-pdf:
    csl: apa.csl
    documentmode: man
    indent: true
    include-in-header: 
      text: |
        \usepackage{setspace}
        \linespread{2}
        \renewcommand{\footnotesize}{\fontsize{8}{10}\selectfont}
bibliography: References.bib
---
Since the Stonewall riots, queer characters have flourished in the mass media, reaching their peak in the information era. As the primary audience for queer media characters, the LGBTQ+ community is claimed to be both positively and negatively impacted by these characters [e.g., @craig_media:_2015;@nolke_making_2018]. While queer characters can favorably impact LGBTQ+ individuals’ identity development and self-esteem, stereotypical representations that lack intersectionality may result in stigmatization and negative mental outcomes. Nevertheless, few studies have compared queer characters’ impacts on different LGBTQ+ subgroups, probably because they ignored the emergence of more marginal groups (e.g., asexual). Additionally, no established instruments have explored how perceived character authenticity or intersectionality may contribute to different psychological well-being outcomes. Knowing LGBTQ+ individuals' diverse needs and experiences with queer media representation is important as it can call for more diverse and inclusive queer media representations. Through developing a reliable instrument on queer media characters’ psychological impacts and conducting worldwide data collection across different LGBTQ+ generations, this study aimed to contribute to a deeper understanding of queer characters’ psychological impacts on different LGBTQ+ groups. 

# Literature Review

## LGBTQ+ Community and Queer Media Characters

@IpsosLimited2024 has found that 17% of Generation Zers^[Generation Z (born between 1996-2012), Millennials (born between 1980-1995), Generation X (born between 1966-1979) and Baby Boomers (born between 1945-1965).] identified as part of the LGBTQ+ community, including identities such as lesbian, gay, bisexual, transgender, queer, asexual, and non-binary. This indicates a significant increase compared with prior generations, with only 11% for Millennials, 6% for Generation Xers, and 5% for Baby Boomers. The evolution within the LGBTQ+ community is accompanied by the flourishing of queer characters in TV shows and films that cater to their needs for identity affirmation and psychological belonging. For instance, the past ten years have witnessed a more than 300% increase in the number of LGBTQ+ characters on broadcast [@GLAAD2024]. Compared with earlier queer characters that often feature heavy stereotypes (e.g., Frank-N-Furter in *Rocky Horror*), queer characters nowadays feature more multidimensional personalities and diversity, indicating progress in the representation of queer lives in media.

## Queer Media Characters’ Positive Impacts on the LGBTQ+ Community

@toomey_coping_2018 indicated that LGBTQ+ individuals may rely on social and cultural resources to enhance identity affirmation and cope with stress. Prior studies found that queer media characters can positively affect LGBTQ+ individuals as an effective coping strategy. @gomillion_influence_2011 conducted surveys and interviews on lesbian, gay, and bisexual (LGB) youth from Texas, suggesting that queer media characters, as role models, could positively affect LGB youth’s self-identity by enhancing their self-esteem and courage. While @gomillion_influence_2011 ignored transgenders and genderqueers, @craig_media:_2015 showed that queer media characters could help LGBTQ youth improve their self-assurance and build relationships with people having shared identities. Nevertheless, prior studies convergently focused on queer characters’ impacts on LGBTQ+ youth in the United States, ignoring cross-generation and cross-country comparisons, which may result in low external validity of the findings. Additionally, these studies barely compared different sexual orientations and gender identities in the LGBTQ+ community, which may neglect more marginalized groups’ perceptions and experiences (e.g., asexual and pansexual). 

## Queer Media Stereotypes’ Negative Impacts on the LGBTQ+ Community

Some studies have also criticized that queer media characters presenting stereotypes could be harmful to the LGBTQ+ community. @yaksich_consuming_2005 and @guidotto_cashing_2006 indicated that many queer media representations are the commodification of the LGBTQ+ community. The queer media monopoly of ‘perfect homo’ (i.e., flamboyant Caucasian and middle-classed gay men) neglects intersectionality, reinforcing the LGBTQ+ stereotypes in the audience’s perceptions. @nolke_making_2018 identified the intersectional invisibility of queer media representations by applying intersectional analysis of a series of advertisements from 2009 to 2015. The discussion from this study also indicated that the hegemony of queer stereotypes and the lack of intersectionality could be harmful to the LGBTQ+ community by bringing them lower confidence and mental illnesses (e.g., depressive disorders). 

# Method

## Participants

## Measures

## Procedure

# Results

# Discussion

## Limitations and Future Directions

## Conclusion

# References

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::


# Appendix

# Title for Appendix
